### ISSUE TITLE
"token" property missing in autocomplete events

### ISSUE THREAD

**Issue by wendt88** [NativeScript/nativescript-ui-feedback#1153]
Packages:
```
nativescript-ui-autocomplete: 4.1.0
tns-core-modules: 5.4.0
nativescript-vue: 2.2.0
```

trying [this example](https://github.com/NativeScript/nativescript-ui-samples-vue/tree/master/autocomplete/app/examples/CustomToken) there is the `token` in the arguments of  each event (`tokenAdded`, `tokenRemoved`, `tokenSelected`, `tokenDeselected`)
But if I add an `setLoadSuggestionsAsync`, the token property is `null`.

with `nativescript-ui-autocomplete` version `4.0.0`, it worked.

### What I have to do:
an autocomplete component with async data fetching, combined with primary keys ([Custom Tokens](https://github.com/NativeScript/nativescript-ui-feedback/issues/65#event-2390852848)) to get at the end an array of it primary keys

**Comment by zbranzov** [comment]
Fixed in nativescript-ui-autocomplete@4.1.1

**Comment by wendt88** [comment]
It seems still missing in the `didAutoComplete`-event, which I have to use for `displayMode`: `AutoCompleteDisplayMode.Plain`. because there the `tokenAdded`-event does not triggers there (not sure if this is correct or a bug)

**Comment by tgpetrov** [comment]
@wendt88 This is expected. The tokenAdded/tokenRemoved/tokenSelected/tokenDeselected are intended for usage in AutoCompleteDisplayMode.Tokens, while didAutoComplete is intended for usage in AutoCompleteDisplayMode.Plain. Since only in mode Tokens a 'token' is actually added in the AutoComplete, the token is available only in the token-related events. In Plain mode just text is added in the AutoComplete and only text is present in the related event.

**Comment by tgpetrov** [comment]
@wendt88 just wanted to let you know that we revised this logic and with the latest version of nativescript-ui-autocomplete, the token is included in the didAutoComplete event args in both modes - Token and Plain.

**Comment by wendt88** [comment]
Perfect, Thanks!
