### ISSUE TITLE
RadListView [Android] RecyclerView$ViewHolder.itemView on a null object reference

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/nativescript-ui-feedback#1206]
This error appears at random with no reliable repro. Possible to just guard this condition?
```
System.err: java.lang.NullPointerException: Attempt to read from field 'android.view.View androidx.recyclerview.widget.RecyclerView$ViewHolder.itemView' on a null object reference
System.err:     at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6795)
System.err:     at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5975)
System.err:     at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
System.err:     at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
System.err:     at androidx.recyclerview.widget.LayoutState.next(LayoutState.java:100)
```

### Which platform(s) does your issue occur on?

Android

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI plugin version:** nativescript-ui-listview 7.0.2
- **CLI:** 6.0.2
- **Cross-platform modules:** 6.0.6
- **Runtime(s):** tns-android 6.0.1

### Please tell us how to recreate the issue in as much detail as possible.

Unfortunately this is purely random and appears can happen at anytime but most likely is result of user navigating into and away from a view with RLV on it. Can it just be guarded to not crash an app?

**Comment by marast78** [comment]
I have the same issue below full exception message

`JS: ERROR Error: java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling com.telerik.widget.list.RadListView{727f0ae VFED..... ......I. 0,0-1080,1557 #16}, adapter:com.telerik.widget.list.ListViewWrapperAdapter@1987676, layout:androidx.recyclerview.widget.LinearLayoutManager@42279dc, context:com.tns.NativeScriptActivity@d3bdca
JS:     androidx.recyclerview.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:2880)
JS:     androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onChanged(RecyclerView.java:5281)
JS:     androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyChanged(RecyclerView.java:11997)
JS:     androidx.recyclerview.widget.RecyclerView$Adapter.notifyDataSetChanged(RecyclerView.java:7070)
JS:     com.telerik.widget.list.ListViewWrapperAdapter.setBottomIndicatorView(ListViewWrapperAdapter.java:122)
JS:     com.telerik.widget.list.ListViewWrapperAdapter.updateOnDemandSettings(ListViewWrapperAdapter.java:320)
JS:     com.telerik.widget....
System.err: An uncaught Exception occurred on "main" thread.
System.err: Attempt to read from field 'android.view.View androidx.recyclerview.widget.RecyclerView$ViewHolder.itemView' on a null object reference
System.err: 
System.err: StackTrace:
System.err: java.lang.NullPointerException: Attempt to read from field 'android.view.View androidx.recyclerview.widget.RecyclerView$ViewHolder.itemView' on a null object reference
System.err: 	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6795)
System.err: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5975)
System.err: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
System.err: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
System.err: 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
System.err: 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
System.err: 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
System.err: 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
System.err: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
System.err: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
System.err: 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
System.err: 	at com.telerik.widget.list.RadListView.onLayout(RadListView.java:589)
System.err: 	at android.view.View.layout(View.java:19590)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
System.err: 	at android.view.View.layout(View.java:19590)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
System.err: 	at android.view.View.layout(View.java:19590)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err: 	at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:354)
System.err: 	at android.view.View.layout(View.java:19590)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err: 	at org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:178)
System.err: 	at org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:132)
System.err: 	at android.view.View.layout(View.java:19590)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err: 	at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:354)
System.err: 	at android.view.View.layout(View.java:19590)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err: 	at org.nativescript.widgets.ContentLayout.onLayout(ContentLayout.java:73)
System.err: 	at android.view.View.layout(View.java:19590)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
System.err: 	at android.view.View.layout(View.java:19590)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
System.err: 	at android.view.View.layout(View.java:19590)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
System.err: 	at android.view.View.layout(View.java:19590)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
System.err: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
System.err: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
System.err: 	at android.view.View.layout(View.java:19590)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
System.err: 	at android.view.View.layout(View.java:19590)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
System.err: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
System.err: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
System.err: 	at android.view.View.layout(View.java:19590)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
System.err: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:758)
System.err: 	at android.view.View.layout(View.java:19590)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2484)
System.err: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2200)
System.err: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
System.err: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
System.err: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
System.err: 	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
System.err: 	at android.view.Choreographer.doFrame(Choreographer.java:658)
System.err: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
System.err: 	at android.os.Handler.handleCallback(Handler.java:789)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:98)
System.err: 	at android.os.Looper.loop(Looper.java:164)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

**Comment by NeriCodec** [comment]
I have the same problem here:

System.err: Attempt to read from field 'android.view.View androidx.recyclerview.widget.RecyclerView$ViewHolder.itemView' on a null object reference
System.err: 
System.err: StackTrace:
System.err: java.lang.NullPointerException: Attempt to read from field 'android.view.View androidx.recyclerview.widget.RecyclerView$ViewHolder.itemView' on a null object reference
System.err:     at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6795)
System.err:     at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5975)
System.err:     at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
System.err:     at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
System.err:     at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
System.err:     at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
System.err:     at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
System.err:     at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
System.err:     at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
System.err:     at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
System.err:     at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
System.err:     at com.telerik.widget.list.RadListView.onLayout(RadListView.java:598)
System.err:     at android.view.View.layout(View.java:20960)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6279)
System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
System.err:     at android.view.View.layout(View.java:20960)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6279)
System.err:     at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:354)
System.err:     at android.view.View.layout(View.java:20960)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6279)
System.err:     at android.widget.ListView.setupChild(ListView.java:2201)
System.err:     at android.widget.ListView.makeAndAddView(ListView.java:2085)
System.err:     at android.widget.ListView.fillDown(ListView.java:797)
System.err:     at android.widget.ListView.fillFromTop(ListView.java:865)
System.err:     at android.widget.ListView.layoutChildren(ListView.java:1816)
System.err:     at android.widget.AbsListView.onLayout(AbsListView.java:2249)
System.err:     at android.widget.HwAbsListView.onLayout(HwAbsListView.java:345)
System.err:     at android.view.View.layout(View.java:20960)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6279)
System.err:     at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:354)
System.err:     at android.view.View.layout(View.java:20960)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6279)
System.err:     at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:354)
System.err:     at android.view.View.layout(View.java:20960)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6279)
System.err:     at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:354)
System.err:     at android.view.View.layout(View.java:20960)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6279)
System.err:     at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     at org.nativescript.widgets.ContentLayout.onLayout(ContentLayout.java:73)
System.err:     at android.view.View.layout(View.java:20960)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6279)
System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
System.err:     at android.view.View.layout(View.java:20960)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6279)
System.err:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1842)
System.err:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1686)
System.err:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1595)
System.err:     at android.view.View.layout(View.java:20960)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6279)
System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
System.err:     at android.view.View.layout(View.java:20960)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6279)
System.err:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1842)
System.err:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1686)
System.err:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1595)
System.err:     at android.view.View.layout(View.java:20960)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6279)
System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
System.err:     at com.android.internal.policy.DecorView.onLayout(DecorView.java:926)
System.err:     at android.view.View.layout(View.java:20960)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6279)
System.err:     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3037)
System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2545)
System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1636)
System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7946)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:893)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:812)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
System.err:     at android.os.Handler.handleCallback(Handler.java:907)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:105)
System.err:     at android.os.Looper.loop(Looper.java:216)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7625)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
File change detected. Starting incremental webpack compilation...

This issue appear in new version

**Comment by zbranzov** [comment]
Possibly fixed in nativescript-ui-listview@7.0.5

**Comment by marast78** [comment]
> Possibly fixed in nativescript-ui-listview@7.0.5

Unfortunately, the issue **was not solved** :confused: I got an error like below, but it's still related to the earlier issue, which I've noticed and reported before. If I use VSC and debug my application with NativeScript's extension, it occurs each time but while I use an external terminal that happens occasionally (the same happens on a real device).

I use Linux/Ubuntu 18.04 and {N} v6.1.2. Under iOS, everything works well.

`System.err: StackTrace:
System.err: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 5(offset:5).state:6 com.telerik.widget.list.RadListView{1bd4c32 VFED..... ......ID 0,0-1080,1557 #14}, adapter:com.telerik.widget.list.ListViewWrapperAdapter@39670a3, layout:androidx.recyclerview.widget.LinearLayoutManager@5fa6b00, context:com.tns.NativeScriptActivity@3041286
System.err: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5923)
System.err: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
System.err: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
System.err: 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
System.err: 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
System.err: 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
System.err: 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
System.err: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
System.err: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
System.err: 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
System.err: 	at com.telerik.widget.list.RadListView.onLayout(RadListView.java:598)
System.err: 	at android.view.View.layout(View.java:20672)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
System.err: 	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
System.err: 	at android.view.View.layout(View.java:20672)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
System.err: 	at android.view.View.layout(View.java:20672)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err: 	at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:354)
System.err: 	at android.view.View.layout(View.java:20672)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err: 	at org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:178)
System.err: 	at org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:132)
System.err: 	at android.view.View.layout(View.java:20672)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err: 	at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:354)
System.err: 	at android.view.View.layout(View.java:20672)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err: 	at org.nativescript.widgets.ContentLayout.onLayout(ContentLayout.java:73)

System.err: 	at android.view.View.layout(View.java:20672)

System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6194)

System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)

System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
System.err: 	at android.view.View.layout(View.java:20672)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
System.err: 	at android.view.View.layout(View.java:20672)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6194)

System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)

System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)

System.err: 	at android.view.View.layout(View.java:20672)

System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6194)

System.err: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)

System.err: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)

System.err: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)

System.err: 	at android.view.View.layout(View.java:20672)

System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6194)

System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)

System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)

System.err: 	at android.view.View.layout(View.java:20672)

System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6194)

System.err: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)

System.err: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)

System.err: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)

System.err: 	at android.view.View.layout(View.java:20672)

System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6194)

System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)

System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)

System.err: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)

System.err: 	at android.view.View.layout(View.java:20672)

System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6194)

System.err: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2792)

System.err: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2319)

System.err: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)

System.err: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)

System.err: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)

System.err: 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)

System.err: 	at android.view.Choreographer.doFrame(Choreographer.java:696)

System.err: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
System.err: 	at android.os.Handler.handleCallback(Handler.java:873)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)

System.err: 	at android.os.Looper.loop(Looper.java:193)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

**Comment by VladimirAmiorkov** [comment]
Hi @marast78 ,

Does that happen during debug sessions while the debugger is stopped at a row or ? If so can you give us step by step of where your place break points when that error occurs, also if you can let us know on which Android API you are observing this it would be of much help.

**Comment by marast78** [comment]
Hi @VladimirAmiorkov, I've fixed my issue :) I've got wrong handled events of the listview. Now it works perfectly!

**Comment by ShyshkovOleg** [comment]
@marast78 @ Could you provide code example of wrong handled events? I have the same issue but could not catch them...
Thank you in advance(DZIĘKUJĘ)....

**Comment by marast78** [comment]
@ShyshkovOleg I got the issue only with onLoadMore, below my code

```javascript
onLoadMoreItemsRequested(args: ListViewEventData) {
        let listView: RadListView = args.object;
        if(this.nextPage > this.currentPage && this.nextPage>1) {
            setTimeout(() => {
                this.pullItems(this.nextPage);
                listView.notifyLoadOnDemandFinished();
            }, 500);
            args.returnValue = true;
        } else {
            listView.notifyLoadOnDemandFinished(true);
            args.returnValue = false;
        }
    }
```
As you see I finish a loading process if no more items exists in my data or there were loaded first collection.
